# Generated by Django 6.0 on 2025-12-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('admin', 'Admin')], default='basic', max_length=20),
        ),
    ]
