# Generated by Django 6.0 on 2026-01-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_organizationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
    ]
