# Generated by Django 6.0 on 2025-12-28 23:27
# Fixed for PostgreSQL + Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.contrib.postgres.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_folder_document_folder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),

        migrations.AlterField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=True),
        ),

        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='document_search_vector_gin',
            ),
        ),
    ]
