# Generated by Django 6.0 on 2025-12-28 23:27
# Compatible with Django 4.2+

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_folder_document_folder"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="document",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
