# Generated by Django 6.0 on 2025-12-28 23:34
# Fixed for Django 4.2 + PostgreSQL (safe on prod)

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options_alter_document_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 🚫 DO NOT remove document_extracted_text_gin
        # It never existed in the DB (failed earlier), removing it crashes migrations

        # ✅ Add tsvector column
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),

        # ✅ Populate search_vector for existing rows
        migrations.RunSQL(
            sql="""
                UPDATE documents_document
                SET search_vector =
                    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(extracted_text, '')), 'B');
            """,
            reverse_sql="""
                UPDATE documents_document
                SET search_vector = NULL;
            """,
        ),

        # ✅ Valid GIN index on TSVECTOR (this works)
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='document_search_vector_gin',
            ),
        ),
    ]
