# Generated by Django 6.0 on 2025-12-28 23:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_options_alter_document_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ❌ Remove invalid GIN index on TextField
        migrations.RemoveIndex(
            model_name='document',
            name='document_extracted_text_gin',
        ),

        # ✅ Add tsvector column
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),

        # 🚀 Populate search_vector for existing documents
        migrations.RunSQL(
            sql="""
                UPDATE documents_document
                SET search_vector =
                    setweight(to_tsvector('english', coalesce(file, '')), 'A') ||
                    setweight(to_tsvector('english', coalesce(extracted_text, '')), 'B');
            """,
            reverse_sql="""
                UPDATE documents_document
                SET search_vector = NULL;
            """,
        ),

        # 🚀 Valid GIN index on tsvector
        migrations.AddIndex(
            model_name='document',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['search_vector'],
                name='document_search_vector_gin'
            ),
        ),
    ]
