# Generated by Django 6.0 on 2025-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_document_extracted_text_gin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='document_search_vector_gin',
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
