# Generated by Django 6.0 on 2025-12-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_folder_options_folder_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
