# Generated by Django 6.0 on 2026-01-03 15:02
# Fixed for PostgreSQL + Django 4.2

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_file_size'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='document',
            index=GinIndex(
                name='documents_d_search__05a045_gin',
                fields=['search_vector'],
            ),
        ),
    ]
