# Generated by Django 6.0 on 2026-01-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_options_alter_organization_options_and_more'),
        ('documents', '0010_document_organization_alter_document_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='document_single_owner_or_org',
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('name', 'parent', 'owner', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner__isnull', False), ('organization__isnull', True)), models.Q(('owner__isnull', True), ('organization__isnull', False)), models.Q(('owner__isnull', True), ('organization__isnull', True)), _connector='OR'), name='document_valid_ownership_scope'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documentaccess',
            unique_together={('document', 'user')},
        ),
    ]
