# Generated by Django 6.0 on 2026-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
